### PR TITLE
Update to Scala 3.3 LTS

### PR DESCRIPTION
**Pull request by mdedetrich**
This is currently a WIP PR to test out if there are any potential issues with Scala 3.3 by using RC3. Once Scala 3.3 is properly released I will update this PR.

Scala 3.3 is a big release since its LTS, which means it will be supported for a long time (critical bugs/security fixes will be backported to the 3.3 branch) so its a good idea to prune out any potential issues before the release is made.

### CODE REVIEW

**Comment by mdedetrich** [comment]
Okay so reason behind build failures is that scala-native doesn't support 3.3.0-RC3 yet

**Comment by mdedetrich** [comment]
Bump to RC5 which was just released

**Comment by mdedetrich** [comment]
Bump to RC6 which was just released

**Comment by mdedetrich** [comment]
@xuwei-k @sirthias PR is now ready to review. Scala 3.3 LTS was just released and all tests passed.

Since https://github.com/sirthias/parboiled2/pull/417#issuecomment-1455714329 merged a technically breaking change, its probably a good idea to release parboiled2 with major version increased after this PR is merged.

**Comment by sirthias** [comment]
Thank you, Matthew!
I'll publish version 2.5.0 today then...

**Pull request merged**
