### PR TITLE
Added Markdown Readme. Started to improve Doc

### PR DESCRIPTION
**Pull request by tampler**

### CODE REVIEW

**Comment by sirthias** [comment]
Thank you, Boris, for this patch.
One question: Why did you decide to move the whole README to Markdown?
This way it's hard to see what parts of it you changed/improved/added...

**Comment by tampler** [comment]
The reasoning was that MD is the standard doc format and most devs know how to work with that.
RST or whatever it is some outdated stuff that nobody knows how to use.

I actually started this since I wanted to convert this MD to my ebook. My device understands MD and PDF, which is easily converted from MD.

1. This format is kind of dummy to say at least. I may want to add docs, examples and more, but won't do that in that dummy format.

2. Another reason is the age of the docs. Scala 2.11 can be immediately removed and you should compare not to parser combinators, but to Antlr and FastParse.

3. There's a work on Shapeless 3 for Dotty. I may want to contribute in this area too

**Comment by tampler** [comment]
There's also a community call to improve docs, as you may check [on gitter](https://gitter.im/sirthias/parboiled2)

**Comment by sirthias** [comment]
Yes, you are right in that reStructuredText appears to have "lost" the competition with Markdown with regard to github README/docs popularity.
I also write all my docs in Markdown now and this old README is a left-over from previous days.

So, your effort to convert things to MD is indeed very welcome!

However, I still think it'd be better to split this PR into two commits:
One containing merely the RST -> MD conversion and one (or more) with all additions/changes/etc.

But now that you appear to have both merged into one, how hard would you think it is to split things up?

**Comment by tampler** [comment]
Mathias, 

I have a better offer to you. We don't need to convert the old doc into the new doc one-by-one. The true goal is to make a short, clean, striking and easy-to-use doc with examples for the benefit of old and new users.

I marked this PR as a WIP to add more improvements and possibly split it to several parts, like Installation, Basic Use, Adv Use and so on.

I'm doing this cos I wanna have a reference in hands, which I may reuse a year later, when I forget most tricks I used to implement my own parser. 

So good doc is vital. Let me improve it gradually and make a good PR

**Comment by tampler** [comment]
First pass validation finished. You may merge this now

Let both RST and MD versions live for some time

**Comment by sirthias** [comment]
Thank you, Boris!
Your work on this conversion to MD is much appreciated!

**Pull request merged**
