### PR TITLE
Add windows-latest to ci matrix

### PR DESCRIPTION
**Pull request by mdedetrich**
This PR adds windows to the ci matrix. I presume that since Parboiled2 is used in some critical Scala OS components, making sure it works on windows is a good idea. On the other hand it does explode the CI matrix a bit, so I understand if you don't want to merge the PR.

Only other additional thing to note is that `githubWorkflowOSes` has no effect on what OS is used to pubish Parboild2, this will always be hardcoded against `ubuntu-latest`.

### CODE REVIEW

**Comment by mdedetrich** [comment]
Well thats interesting, seems like some workflow failed because the cache exceeded some timeout. There is an existing PR to add timeout capability (see https://github.com/sbt/sbt-github-actions/pull/98), so I will work on this further when that lands.

**Comment by sirthias** [comment]
Ok, thank you, Matthew!

**Comment by mdedetrich** [comment]
Do you mind re-running the CI (i.e. re-run all failed jobs)? Just want to see if its consistent or not (might be a cold run issue).

**Comment by mdedetrich** [comment]
Interesting

```
[error] LLVM ERROR: out of memory
[error] Allocation failed
[error] LLVM ERROR: out of memory
[error] Allocation failed
[error] PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
[error] PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
[error] Stack dump:
[error] Stack dump:
[error] 0.	Program arguments: "C:\\Program Files\\LLVM\\bin\\clang.exe" -c D:\\a\\parboiled2\\parboiled2\\parboiled-core\\.native\\target\\scala-3.2.2\\native-test\\1.ll -o D:\\a\\parboiled2\\parboiled2\\parboiled-core\\.native\\target\\scala-3.2.2\\native-test\\1.ll.o -Wno-override-module -g -fexceptions -funwind-tables -fvisibility=hidden -O0 -Qunused-arguments
[error] 1.	Code generation
[error] Exception Code: 0xC000001D
[error] 0.	Program arguments: "C:\\Program Files\\LLVM\\bin\\clang.exe" -c D:\\a\\parboiled2\\parboiled2\\parboiled-core\\.native\\target\\scala-3.2.2\\native-test\\0.ll -o D:\\a\\parboiled2\\parboiled2\\parboiled-core\\.native\\target\\scala-3.2.2\\native-test\\0.ll.o -Wno-override-module -g -fexceptions -funwind-tables -fvisibility=hidden -O0 -Qunused-arguments
[error] 1.	Code generation
[error] 2.	Running pass 'Function Pass Manager' on module 'D:\a\parboiled2\parboiled2\parboiled-core\.native\target\scala-3.2.2\native-test\0.ll'.
[error] 3.	Running pass 'X86 Assembly Printer' on function '@"_SM34org.parboiled2.ActionSpec$$anon$13D10wrapped$16L34org.parboiled2.ActionSpec$$anon$13zEPT34org.parboiled2.ActionSpec$$anon$13"'
[error] Exception Code: 0xC000001D
[error] 0x00007FF743DF6886, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x6A6886 byte(s)
[error] 0x00007FF9D385BAB4, C:\Windows\System32\ucrtbase.dll(0x00007FF9D37E0000) + 0x7BAB4 byte(s)
[error] 0x00007FF9D385CA81, C:\Windows\System32\ucrtbase.dll(0x00007FF9D37E0000) + 0x7CA81 byte(s)
[error] 0x00007FF743DBAEF7, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x66AEF7 byte(s)
[error] 0x00007FF743DBAF32, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x66AF32 byte(s)
[error] 0x00007FF9A3332721, C:\Program Files\LLVM\bin\MSVCP140.dll(0x00007FF9A3320000) + 0x12721 byte(s)
[error] 0x00007FF9D38575A6, C:\Windows\System32\ucrtbase.dll(0x00007FF9D37E0000) + 0x775A6 byte(s)
[error] 0x00007FF74793929B, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x41E929B byte(s)
[error] 0x00007FF743A96008, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x346008 byte(s)
[error] 0x00007FF743C076B1, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x4B76B1 byte(s)
[error] 0x00007FF743BFF8D2, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x4AF8D2 byte(s)
[error] 0x00007FF743BFF5D2, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x4AF5D2 byte(s)
[error] 0x00007FF7452CE06A, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x1B7E06A byte(s)
[error] 0x00007FF7452CDD85, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x1B7DD85 byte(s)
[error] 0x00007FF743FC5A08, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x875A08 byte(s)
[error] 0x00007FF743FBD4D6, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x86D4D6 byte(s)
[error] 0x00007FF743992C16, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x242C16 byte(s)
[error] 0x00007FF744031C4B, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x8E1C4B byte(s)
[error] 0x00007FF743B103A8, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x3C03A8 byte(s)
[error] 0x00007FF743B160B3, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x3C60B3 byte(s)
[error] 0x00007FF743B109CF, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x3C09CF byte(s)
[error] 0x00007FF744EA036C, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x175036C byte(s)
[error] 0x00007FF745229F04, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x1AD9F04 byte(s)
[error] 0x00007FF745196D02, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x1A46D02 byte(s)
[error] 0x00007FF743F2580D, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x7D580D byte(s)
[error] 0x00007FF743FB6E9E, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x866E9E byte(s)
[error] 0x00007FF743757B1B, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x7B1B byte(s)
[error] 0x00007FF743754A73, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x4A73 byte(s)
[error] 0x00007FF744F77BD6, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x1827BD6 byte(s)
[error] 0x00007FF743DBA78F, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x66A78F byte(s)
[error] 0x00007FF744F7795B, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x182795B byte(s)
[error] 0x00007FF743EE2D15, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x792D15 byte(s)
[error] 0x00007FF743EE305D, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x79305D byte(s)
[error] 0x00007FF743EFD0FC, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x7AD0FC byte(s)
[error] 0x00007FF74375[438](https://github.com/sirthias/parboiled2/actions/runs/4362088244/jobs/7627420232#step:10:439)F, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x438F byte(s)
[error] 0x00007FF74793A770, C:\Program Files\LLVM\bin\clang.exe(0x00007FF743750000) + 0x41EA770 byte(s)
[error] 0x00007FF9D5314DE0, C:\Windows\System32\KERNEL32.DLL(0x00007FF9D5300000) + 0x14DE0 byte(s)
[error] 0x00007FF9D613E40B, C:\Windows\SYSTEM32\ntdll.dll(0x00007FF9D60C0000) + 0x7E40B byte(s)
[error] clang: error: clang frontend command failed due to signal (use -v to see invocation)
```

Should I file an issue for this?

**Comment by sirthias** [comment]
Thank you!

**Comment by mdedetrich** [comment]
I would consider the PR to be ready to review right now. There were 2 problems, the first one was with the timeout did appear to be a cold cache issue (never experienced the issue after every subsequent run) and the latter problem appears to be a Windows specific one wrt how page size's work on the OS.

I have run the CI ~8 times now and its passed every time so at least for now it doesn't appear to be flaky (and if it is you can always ignore the CI/fix it later).

**Pull request merged**
