### PR TITLE
A basic parser showing showing BNF & highlighting the parse tree

### PR DESCRIPTION
**Pull request by ChrisCoffey**
I was having trouble finding examples of using the library to selectively extract tokens from a document & ended up writing a very simple example. Hopefully this will help other folks like myself in the future.

### CODE REVIEW

**Comment by sirthias** [comment]
Thanks, Chris, for this nice example!
This could indeed become a valuable something to look at for new users.

**Comment by ChrisCoffey** [comment]
@sirthias I've updated this and cleaned it up following your comments.

**Comment by sirthias** [comment]
Thanks, Chris.
I'll look at it as soon as my time permits.

**Comment by sirthias** [comment]
Sorry for taking this long in finally getting this merged!

**Pull request merged**
