### PR TITLE
OSGi manifests via sbt-osgi plugin

### PR DESCRIPTION
**Pull request by FeiWongReed**
Hi. 

Could you merge this pull request just to enable OSGi manifests for your library? 

Also could you be so kind to OSGify parbolied v1, just to enable Spray to work in OSGi containers? Here is my pull request for parboiled v1: https://github.com/sirthias/parboiled/pull/92

### CODE REVIEW

**Comment by sirthias** [comment]
Thank you!
I have to say though that I will spent *zero time* from my side on trying to maintaining this OSGi support.

**Comment by sirthias** [comment]
Another thing: I don't think getting spray to work in OSGi containers is easily done.
People have already spent countless hours on this and I don't want to be kept busy with things that add no value to the very large majority of users.
So, no, unfortunately I will not be able to help with getting spray to work with OSGi.

**Comment by FeiWongReed** [comment]
Spray works for me for now but there is still many work to do.

**Comment by FeiWongReed** [comment]
Could you also merge same patch for parboiled v1 and make a release?

**Comment by sirthias** [comment]
@FeiWongReed Unfortunately I currently have no capacity for that, sorry.

**Comment by FeiWongReed** [comment]
I had created pull request for v1, everything is required to do is just accept P/R and run sbt publish...

**Comment by sirthias** [comment]
Unfortunately the release process is a bit more involved.
It entails updating dependencies and making sure that everything still runs, updating the changelog and the documentation, then going through the sonatype publishing process, then updating depending libraries, etc.

Also, the master branch is currently in a state where version 2.2 is almost done.
However, 2.2. brings significant changes which require substantial updates to the documentation.
Releasing 2.2 will require several days of work from my side.

**Comment by FeiWongReed** [comment]
Ok, but may you, at least, accept P/R?

**Comment by sirthias** [comment]
I already merged it to master 7 hours ago.

**Comment by FeiWongReed** [comment]
I'm speaking about this one: https://github.com/sirthias/parboiled/pull/92

**Pull request merged**
