### PR TITLE
Build for Scala 2.13.0-M4

### PR DESCRIPTION
**Pull request by theon**
Note: I've had to remove argonaut from the JMH benchmarks as it has not been released against Scala 2.13 yet.

### CODE REVIEW

**Comment by pshirshov** [comment]
Why not to drop argonaut in favor of circe?

**Comment by sirthias** [comment]
Thank you, Ian!

**Comment by theon** [comment]
No problem. When you get a chance, could we get a Scala 2.13 build published?

**Comment by sirthias** [comment]
Just published release 2.1.5, which is also available for 2.13.0-M4

**Pull request merged**
