### PR TITLE
Minimal HList to decouple from shapeless

### PR DESCRIPTION
**Pull request by rossabaker**
parboiled2's dependency on shapeless means that any application that uses parboiled2, directly or transitively, must pin to that fast-moving dependency.

This declares a minimal `org.parboiled2.support.HList`, extracted from shapeless, to replace the shapeless dependency.  shapeless remains in test scope only for `illTyped`, which could be replaced with some more effort.  More operations could be added to this `HList` if desired, but `HList` is _mostly_ an implementation detail, and `::` and `reverse` are sufficient to compile all the tests.

/cc https://github.com/http4s/http4s/issues/646

### CODE REVIEW

**Comment by sirthias** [comment]
Thanks, Ross!

> parboiled2's dependency on shapeless means that any application that uses parboiled2, directly or transitively, must pin to that fast-moving dependency.

My impression is that @milessabin is very much aware of the position that shapeless has in common dependency trees and therefore manages binary compatibility quite carefully.
Of course we could move off the shapeless dependency with something like this patch but in return we'd forego seamless integration with the growing number of other tools that build on top of shapeless, as well as the wealth of type logic that shapeless already brings to the table itself.
This is not a trade-off that I'd be willing to make without proper consideration.

Can you elaborate a bit more on the problems that you encountered with regard to incompatibilities between shapeless versions?

**Comment by rossabaker** [comment]
Shapeless only guarantees binary compatibility across minor versions.  This has caused me pain twice now:

1. In the past, circe was on shapeless-2.2 at a time that parboiled2 was on shapeless-2.1.  These couldn't coexist in the same app.  (Both now support 2.3.)
2. I now have a large shapeless-2.2 codebase, but the latest parboiled2 has moved on to shapeless-2.3.  I have to upgrade shapeless everywhere to use the latest parboiled2.

`HList` is prevalent in the public API, but I can't recall a case that I've ever taken advantage of it being a `shapeless.HList` rather than an implementation detail behind parboiled2's combinators.  My experience has been that parboiled2 works great *alongside* the shapeless ecosystem, but causes binary compatibility woes by trying to be *part* of it.  But I can certainly understand that my experience may not be representative.

**Comment by sirthias** [comment]
Thanks, Ross, for these details. I see where your pain comes from.
Part of it appears to be rooted in me not upgrading pb2 from shapeless 2.1 to shapeless 2.2 fast enough at the time. And the other part in not making a shapeless 2.2 release available after the upgrade to shapeless 2.3.

Seeing that moving between shapeless versions isn't very hard on the pb2 end of things it's not a problem for me to release artifacts for alternative shapeless versions alongside the main release.
Also, I'd expect migrations to and between future shapeless versions to be rather easy.

So, what if I promised you that you could always just ping me whenever a shapeless incompatibility arises on your end and I'd try to take care of it ASAP?
Would that help?

**Comment by timperrett** [comment]
Hey @sirthias, long time no chat. Hope all is well at your end! Just read this thread and wanted to share a view on it: it strikes me that shapeless is just an implementation detail, and if PB2 is releasing more frequently, then it causes a downstream ripple effect where all subsequent libraries will also have to upgrade frequently, causing more release burden for all. I guess it just strikes me that a fast moving dependency such as shapeless, for a slow moving library like PB2, may very well not be the best thing, and having some isolation would actually improve PB2 adoption as it would be less dependencies to wrangle. 

With my production maintenance hat on: minimal dependencies are the easiest thing for users over time, so i'm very much +1 on this PR as it will make it easier to adopt http4s.

Hope this helps!

**Comment by milessabin** [comment]
shapeless has a strict binary compatibility policy within minor releases using the same convention as the Scala distribution. shapeless 2.3.0 was released in February and whilst not binary compatible with shapeless 2.2.x is almost completely source compatible with it.

2.2.x => 2.3.z is the only binary incompatible change in the 12 months, so whatever your definition of "fast moving" might be I don't think you could describe it as unreasonably unstable ... living software has to evolve after all.

**Comment by timperrett** [comment]
@milessabin appreciate that, and in a narrow frame I agree. problem is that it doesn't scale: when you're managing literally hundreds upon hundreds of projects, minimal dependency chains are the way to go. The same problem exists for scalaz, scalaz stream and anything else we use a lot of - lining up versions of shapeless with versions of http4s and scodec and and and etc etc becomes tricky. This is not a criticism of shapeless or parboiled specifically, its just the reality of life on the JVM when you have a large system, and we're trying to ease that for both ourselves and others. Naturally we could just maintain internal forks of the whole world, but we're not keen to do that as we want to enable ourselves to give back to the community as much as possible.

**Comment by milessabin** [comment]
@timperrett scodec is on shapeless 2.3.1 just like parboiled. Can't you roll http4s forward?

**Comment by rossabaker** [comment]
http4s is already on the latest parboiled2, and therefore shapeless-2.3.  That's easy. 

What hurts is rolling forward a large shapeless-2.2 codebase so it can use that http4s.  If parboiled2 didn't depend on shapeless, then the http4s and shapeless upgrades could be done on their own schedules.

**Comment by milessabin** [comment]
Wouldn't another option be to forward port the version of parboiled2 that your codebase depends on to shapeless 2.3? I could see that being useful elsewhere.

**Comment by sirthias** [comment]
@rossabaker. It's no problem for me to release a current version of pb2 that's compiled against shapeless 2.2 if that's of any help to you.

**Comment by bryce-anderson** [comment]
I don't recall myself ever using shapeless directly when interacting with PB2: PB2 provides a great interface as it is. Could someone point me to some code using shapeless with PB2? I'd be interested to see what advantages it has over the PB2 provided API.

**Pull request closed without merging**
